// AUTO-GENERATED by scripts/fetch-cms-blogs.mjs — do not edit by hand.
// Published blogs pulled from Supabase at build time and merged into the
// static public Blogs page. No Supabase runtime code ships to the browser.
export const CMS_BLOGS = [
  {
    "id": 1785738933,
    "slug": "llm-ops-keeps-enterprise-ai-alive",
    "title": "LLM Ops: the unglamorous work that keeps enterprise AI alive",
    "description": "",
    "metaTitle": "LLM Ops: How to Keep Enterprise AI Running in Production",
    "metaDescription": "Learn how LLM Ops keeps enterprise AI reliable through cost control, model routing, caching and continuous evaluation in production.",
    "category": "AI Strategy",
    "label": "Blog",
    "date": "Aug 3, 2026",
    "readTime": "12 min read",
    "image": "https://jxfcncdphzctcoiepfhs.supabase.co/storage/v1/object/public/blog-images/1785738169728-whatsapp-image-2026-08-03-at-10-18-42-am.jpeg",
    "imageAlt": "LLM Ops workflow for cost control, model routing, caching and evaluation in enterprise A",
    "author": "Nextdot Digital Solutions Pvt. Ltd.",
    "tags": [],
    "publishedISO": "2026-08-03",
    "relatedBlogs": [
      "integration-layer-decides-whether-hospital-ai-works",
      "ai-agent-governance-gap",
      "why-multi-agent-systems-fail-on-coordination-cost",
      "what-is-agentic-ai-orchestration",
      "token-costs-caching-model-routing-ai-unit-economics"
    ],
    "body": [
      {
        "text": "The demo is the easy part. A model answers a hard question in front of the board, someone signs a budget, and the project is declared real. Six weeks into production the same system is quietly costing four times the estimate, returning wrong answers on inputs nobody tested, and nobody on the team can say why. Gartner predicted that 30 percent of generative AI projects would be abandoned after proof of concept by the end of 2025, citing escalating costs, poor data quality, and unclear value among the reasons (Gartner, July 2024). Most of those projects did not fail because the model was bad. They failed because the layer that keeps a model alive in production was never built.",
        "type": "p"
      },
      {
        "text": "That layer is LLM Ops. It is the least glamorous work in enterprise AI and the part that decides whether anything survives contact with real traffic. If your team can demo but cannot operate, you do not have an AI system. You have a prototype with a large bill attached.",
        "type": "p"
      },
      {
        "text": "What LLM Ops actually is",
        "type": "h2"
      },
      {
        "text": "LLM Ops is the operational discipline around a language model in production. It covers everything that happens after the prompt is written and before the answer reaches a user, plus everything you need to know afterwards to trust that the answer was correct.",
        "type": "p"
      },
      {
        "text": "Think of it as four load-bearing concerns. Cost control, so the system stays economically viable at real volume. Model routing, so each request goes to the cheapest model that can actually handle it. Caching, so you stop paying to answer the same question twice. Evaluation, so you know whether a change made the system better or quietly broke it. None of these appear in a demo. All of them determine whether the system is running or dead a quarter later.",
        "type": "p"
      },
      {
        "text": "The reason this work gets skipped is structural. A demo runs on one prompt, one model, low traffic, and a human watching every output. Production runs on thousands of concurrent requests, mixed difficulty, no human in the loop, and a finance team reading the invoice. The engineering that closes that gap is invisible when it works and catastrophic when it is missing.",
        "type": "p"
      },
      {
        "text": "Cost control: the bill nobody modelled",
        "type": "h2"
      },
      {
        "text": "Per-token prices have been falling for two years, which has convinced a lot of buyers that inference is getting cheap. Aggregate spend tells the opposite story. Menlo Ventures reported that enterprise spending on model APIs more than doubled in the first half of 2025, rising from 3.5 billion dollars to 8.4 billion dollars, even as per-token costs dropped (Menlo Ventures, 2025 Mid-Year LLM Market Update). Prices per token fell and total bills climbed, because consumption grew faster than prices fell.",
        "type": "p"
      },
      {
        "text": "Agentic systems are the main reason. A single agent that reads a document, plans, calls tools, and checks its own work can burn many times the tokens of a simple chatbot reply. When a workflow loops or chains steps, token use compounds. Teams that scaled past the pilot often discovered the true unit cost only when the first full-traffic invoice arrived.",
        "type": "p"
      },
      {
        "text": "Cost control in LLM Ops means treating tokens like any other metered resource. You need per-feature and per-customer cost attribution, so you know which workflow is expensive and whether it earns its keep. You need budgets and rate limits that degrade gracefully instead of failing when a runaway loop starts spending. You need a token accounting habit at the design stage, because a workflow that costs eight rupees per run at pilot volume can cost more than the revenue it supports at scale. The finance question and the architecture question are the same question, and the team that answers it late pays for the answer twice.",
        "type": "p"
      },
      {
        "text": "Model routing: stop sending easy work to expensive models",
        "type": "h2"
      },
      {
        "text": "The single most common waste in enterprise AI is sending every request to the largest available model. It is the safe default. It is also the reason the bill is what it is.",
        "type": "p"
      },
      {
        "text": "Most production traffic is not hard. Classifying an incoming message, extracting a few fields from a form, answering a routine query against a known document: a small, cheap model handles these correctly at a fraction of the cost and latency of a frontier model. The genuinely difficult requests, the ones that need multi-step reasoning or careful judgment, are a minority of the traffic and deserve the expensive model. Routing is the logic that decides which is which.",
        "type": "p"
      },
      {
        "text": "Done well, routing is a system in its own right. A lightweight classifier or a set of rules inspects each request and assigns it to a tier. Easy requests go to a smaller model. Hard requests go to a larger one. Requests that a small model attempts but fails on escalate automatically, so the cheap path is tried first and the expensive path is the fallback rather than the default. The savings are real precisely because the traffic distribution is so skewed toward the easy end.",
        "type": "p"
      },
      {
        "text": "Routing also buys resilience. When one model provider has an outage or a latency spike, a routing layer can redirect traffic to an alternate model instead of taking the whole system down. A system with a single hardcoded model has a single point of failure with someone else's uptime attached to it. Build the routing layer once and you get cost efficiency and failover from the same piece of infrastructure.",
        "type": "p"
      },
      {
        "text": "Caching: paying once to answer a question once",
        "type": "h2"
      },
      {
        "text": "A surprising share of production traffic is repetitive. Users ask the same questions, systems retrieve against the same documents, and prompts share long stretches of identical context. Without caching, you pay full price to compute the same answer again and again.",
        "type": "p"
      },
      {
        "text": "There are two kinds of caching worth building. The first is prompt caching, where the model provider stores the processed form of a long, stable prefix, a system prompt or a large reference document, so that repeated calls reuse it instead of reprocessing it. Providers commonly price these cache reads well below the cost of fresh input tokens, which makes long-context, high-repetition workloads dramatically cheaper and faster [verify]. The second is response caching, where you store the full answer to a request and return it directly when the same or a semantically similar request arrives, skipping the model entirely.",
        "type": "p"
      },
      {
        "text": "Caching is where the unglamorous framing earns its keep. Getting it right means deciding what is safe to cache and for how long, invalidating entries when the underlying data changes, and never serving a stale answer in a context where correctness is regulated. In healthcare and other regulated settings, a cached answer that is out of date is not a performance problem. It is a compliance and liability problem. The cache is only as good as the invalidation logic behind it, and that logic is engineering, not configuration.",
        "type": "p"
      },
      {
        "text": "Evaluation pipelines: knowing whether a change helped",
        "type": "h2"
      },
      {
        "text": "The hardest thing about operating a language model is that it can get worse without anything visibly breaking. A prompt tweak, a model version update on the provider's side, or a change in the incoming data can quietly degrade output quality while every server stays green. If your only signal is user complaints, you find out last, after the damage is done.",
        "type": "p"
      },
      {
        "text": "Evaluation pipelines are the answer, and this is the part most teams skip entirely. You need a held-out set of representative inputs with known good outputs, run automatically against every change before it ships. You need production sampling, where a slice of real traffic is scored continuously, by rules, by a separate model acting as a judge, or by human review on the highest-stakes outputs. You need to catch regressions when the provider silently updates a model underneath you, which happens, and which will move your outputs whether you were watching or not.",
        "type": "p"
      },
      {
        "text": "Without an evaluation pipeline, every deployment is a guess and every model update is a risk you cannot measure. With one, you can change prompts, switch models, and tune routing with evidence instead of hope. This is the difference between operating a system and merely hosting one. It is also the single clearest test of whether a team has run AI in production before, because the teams that have been burned build this first and the teams that have not do not know to ask.",
        "type": "p"
      },
      {
        "text": "The work that decides survival",
        "type": "h2"
      },
      {
        "text": "None of this shows up in a pitch. Cost attribution, routing tiers, cache invalidation, and evaluation suites are invisible when they work. They are also the entire reason a system is still running a year after launch instead of sitting in the 30 percent that got quietly switched off.",
        "type": "p"
      },
      {
        "text": "The pattern is consistent across every enterprise AI deployment that lasts. The team treats the model as one component in an operated system, not as the system itself. They instrument cost from day one. They route by difficulty. They cache what is safe and invalidate what changes. They evaluate continuously so they know, with evidence, whether today's system is better than last week's. This is the work that keeps enterprise AI alive, and it is precisely the work that most buyers do not think to ask about until the bill or the wrong answer forces the question.",
        "type": "p"
      },
      {
        "text": "When you evaluate an AI vendor or an internal team, do not ask whether they can build a demo. Everyone can build a demo now. Ask how they control cost at scale, how they route, what they cache and how they invalidate it, and how they know when the system regresses. The answers to those four questions tell you whether you are looking at a system that will survive production, or a prototype with a large bill attached.",
        "type": "p"
      }
    ]
  },
  {
    "id": 1785581144,
    "slug": "pharmacovigilance-case-processing-ai-opportunity-pharma",
    "title": "Pharmacovigilance case processing: the highest-volume AI opportunity in pharma",
    "description": "",
    "metaTitle": "AI in Pharmacovigilance Case Processing: Pharma Use Cases",
    "metaDescription": "How AI can improve pharmacovigilance case processing, from intake and MedDRA coding to narrative generation, while keeping human review and compliance.",
    "category": "Healthcare",
    "label": "Blog",
    "date": "Aug 1, 2026",
    "readTime": "9 min read",
    "image": "https://jxfcncdphzctcoiepfhs.supabase.co/storage/v1/object/public/blog-images/1785569271033-whatsapp-image-2026-08-01-at-10-29-13-am.jpeg",
    "imageAlt": "AI-powered pharmacovigilance case processing workflow for adverse event reports in pharma",
    "author": "Nextdot Digital Solutions Pvt. Ltd.",
    "tags": [],
    "publishedISO": "2026-08-01",
    "relatedBlogs": [
      "ai-scribes-in-indian-languages-why-english-only-fails-in-opd",
      "ai-agent-governance-gap",
      "hospital-ai-data-security-wall",
      "building-a-small-language-model-for-healthcare-compliance",
      "hospital-ai-readiness-checklist-8-questions-before-you-deploy"
    ],
    "body": [
      {
        "text": "**Pharmacovigilance case processing: the highest-volume AI opportunity in pharma**",
        "type": "h3"
      },
      {
        "text": "Every marketed drug produces a stream of adverse event reports, and every one of those reports is a regulated document with a clock attached. A serious, unexpected case in most jurisdictions has to reach the regulator inside fifteen calendar days. Miss enough of those windows and a marketing authorisation is genuinely at risk. This is the quiet operational load sitting under every pharma safety department, and it is the clearest high-volume case for applied AI anywhere in the industry.",
        "type": "p"
      },
      {
        "text": "Start with the scale, because the scale is the whole argument. The FDA's adverse event database held 30,179,725 reports as of 31 December 2024 and takes in roughly 1.5 million new reports a year (FDA Adverse Event Reporting System, data as of 31 December 2024). That is one regulator, in one country, for drugs and therapeutic biologics alone. Add the EU, Japan, and the WHO global database in Uppsala that India feeds through the Pharmacovigilance Programme of India, and the individual case safety report, the ICSR, becomes the highest-frequency regulated artifact a pharma company produces. Global reporting has been climbing for years, pushed by digital intake channels, patient support programmes, and social media monitoring, with more than 20 million new adverse drug reaction reports logged worldwide in 2024 [verify].",
        "type": "p"
      },
      {
        "text": "Now the part that turns volume into an AI question rather than a hiring question. Each case is still processed largely by hand, the processing is repetitive and expensive, and the work is unforgiving of error. A safety operation that scales by adding case processors is buying linear cost against a workload that grows faster than headcount budgets do.",
        "type": "p"
      },
      {
        "text": "**What one case actually takes**",
        "type": "h2"
      },
      {
        "text": "To see where AI fits, you have to see the assembly line it would join. A single ICSR moves through a fixed sequence, and none of the steps are optional.",
        "type": "p"
      },
      {
        "text": "Intake comes first, and it is messy by nature. A case arrives as a call centre transcript, a scanned form, an email from a physician, a line in a published journal, a fax, or a portal submission. Someone has to read it and decide whether it is even a valid case, which means confirming the four minimum criteria: an identifiable patient, an identifiable reporter, a suspect product, and an adverse event.",
        "type": "p"
      },
      {
        "text": "Triage follows. Is the event serious by the regulatory definition, meaning death, hospitalisation, a congenital anomaly, or a life-threatening outcome. Is it expected against the product label, or unexpected. Those two judgements set the reporting clock and decide whether the case is expedited or periodic.",
        "type": "p"
      },
      {
        "text": "Then data entry into the safety database, structured to the ICH E2B standard so it can be transmitted electronically. Then medical coding, where every reported event, indication, and item of medical history is mapped to a MedDRA term so cases become countable across a global dataset. Then medical review of causality and seriousness. Then a written case narrative, the plain-language account a reviewer reads to understand what happened. Then quality control, then submission through the regulatory gateway, and throughout, duplicate detection so the same event reported through three channels does not become three phantom cases.",
        "type": "p"
      },
      {
        "text": "That is a lot of skilled, deadline-bound labour per case. Multiply it by a mid-size portfolio and the economics explain themselves.",
        "type": "p"
      },
      {
        "text": "**Where AI actually fits, step by step**",
        "type": "h2"
      },
      {
        "text": "The instinct is to ask whether AI can do case processing. The better question is which steps it should touch and which it must not.",
        "type": "p"
      },
      {
        "text": "Intake and triage is the strongest fit. Extracting structured fields from an unstructured source, an email, a transcript, a literature abstract, is exactly what current language models are good at. A model can read an inbound report, pull the patient details, the suspect drug, the event terms, and the reporter, and flag whether the four validity criteria are met. It can make a first pass at seriousness so the fifteen-day cases surface immediately instead of waiting in a queue. This is triage acceleration, not autonomous decision-making, and that distinction matters for every downstream conversation with a regulator.",
        "type": "p"
      },
      {
        "text": "MedDRA coding is the second clear fit, and also the one that punishes overconfidence. Mapping a reporter's phrase, say \"my heart was racing\", to the correct Lowest Level Term inside a dictionary of tens of thousands of terms is high-volume, rules-heavy, and consistency-sensitive. A model can propose codes at speed. It will also occasionally propose a term that is plausible and wrong, and in pharmacovigilance a miscoded event does more than misspell a field. It changes how a signal aggregates. So coding is a suggestion engine with mandatory human confirmation, not an autocoder you trust silently.",
        "type": "p"
      },
      {
        "text": "Narrative generation is where the volume economics get most attractive and the risk gets most subtle. The narrative is a structured retelling of facts already captured in the case, which makes it well suited to generation from the structured record. Done properly, a model drafts the narrative from the coded fields, a medical reviewer edits and signs, and the reviewer spends their time on judgement instead of transcription. Done badly, the model introduces a detail that is not in the source case, and you have a regulated document that says something the reporter never said. The guardrail is strict grounding: the narrative may only contain what the case record contains, and every draft is reviewed against the source before it counts as anything.",
        "type": "p"
      },
      {
        "text": "Duplicate detection and literature screening round out the set. Both are pattern-matching at volume across large text corpora, and both are places where a model earns its keep by shrinking a haystack a human still has to check.",
        "type": "p"
      },
      {
        "text": "**The volume economics, stated plainly**",
        "type": "h2"
      },
      {
        "text": "The reason this is the highest-volume opportunity in pharma AI is arithmetic. Case processing cost scales with case count. Case count is rising. Traditional response is to outsource to lower-cost geographies or add processors, both of which keep cost roughly linear with volume. AI changes the slope. It moves the human effort from data handling to medical judgement rather than removing the people.",
        "type": "p"
      },
      {
        "text": "The realistic model is time reallocation, not headcount elimination. Intake extraction, first-pass coding, and narrative drafting are the hours that a well-scoped system compresses. Medical review, causality assessment, and final sign-off stay with qualified people, because those are the steps a regulator will ask you to defend. A safety operation that gets this split right can absorb a rising case load without a proportional rise in cost, and it can hit fifteen-day deadlines more reliably because triage no longer waits on a person to open the queue. That reliability, the shrinking of missed or late expedited reports, is worth more than the labour saving on most days, since a compliance failure in pharmacovigilance is a regulatory event, not a line item.",
        "type": "p"
      },
      {
        "text": "The pharmacovigilance and drug safety market reflects this pressure. Independent analysts put the broader pharmacovigilance market at 9.64 billion dollars in 2025, growing toward 10.86 billion in 2026 (The Business Research Company, 2026) [verify]. Case volume is the cost driver underneath that number.",
        "type": "p"
      },
      {
        "text": "**Validation is the real project**",
        "type": "h2"
      },
      {
        "text": "Here is the part vendors skip and buyers should not. In pharmacovigilance, the AI is the easy half. The hard half is proving to a regulator that the AI is fit for its regulated purpose, and that is a validation project, not a model project.",
        "type": "p"
      },
      {
        "text": "Any computerised system that touches a GxP record falls under the same expectations as the rest of the safety database. In the United States that means 21 CFR Part 11 for electronic records and signatures, and the GAMP 5 framework from ISPE as the de facto route to computer system validation. The FDA finalised its Computer Software Assurance guidance in September 2025, which reframes validation effort around risk, a change that matters for AI systems specifically because it lets teams concentrate assurance on the steps that can actually harm a patient or a submission. In the EU, ICH E2B(R3) governs how cases are transmitted and GVP Module VI governs how ICSRs are managed. India's framework runs through the Pharmacovigilance Programme of India under the Indian Pharmacopoeia Commission, with a national network of ADR monitoring centres feeding VigiBase, and CDSCO's marketing-authorisation-holder obligations sitting over pharma companies directly [verify].",
        "type": "p"
      },
      {
        "text": "What that adds up to in practice is a set of requirements most AI pilots are not built to meet. Every model output that enters a case needs an audit trail showing what was generated, what a human changed, and who approved it. The system needs versioning, because a model that silently updates is a validated system that quietly became unvalidated. It needs defined behaviour when it is unsure, surfacing low-confidence extractions and codes for review rather than guessing. And it needs a human accountable at every point where a regulated judgement is made, because when a signal is missed, no regulator will accept \"the model coded it\" as an answer.",
        "type": "p"
      },
      {
        "text": "This is why the right posture for AI in pharmacovigilance is assistive by design. The system reads, extracts, proposes, and drafts. A qualified person decides. That posture is the architecture a regulated safety function actually requires, and it deserves no apology. It is the same compliance-aware, human-in-the-loop stance that regulated AI demands across pharma more broadly.",
        "type": "p"
      },
      {
        "text": "**What a safety leader should take from this**",
        "type": "h2"
      },
      {
        "text": "Pharmacovigilance case processing is the highest-volume AI opportunity in pharma because the work is enormous, structured, repetitive, and rising, and because most of it is document handling rather than medical judgement. The value is real and it is bounded. AI compresses intake, coding, and narrative drafting. It does not decide causality, it does not sign a case, and it does not talk to the regulator on your behalf.",
        "type": "p"
      },
      {
        "text": "A Head of Regulatory or a PV lead evaluating this should hold any vendor to three tests. Show me the audit trail on every AI-touched field. Show me the validation package that survives an inspection. Show me where the human decision sits, in writing. A system that answers those three cleanly is worth piloting. One that leads with time saved and goes quiet on validation is selling you a compliance exposure with a productivity label on it.",
        "type": "p"
      }
    ]
  }
];
