// AUTO-GENERATED by scripts/gen-static-index.mjs — do not edit by hand.
// Slug + title of the hardcoded static blogs, for the CMS Related picker search.
export const STATIC_BLOG_INDEX: { slug: string; title: string }[] = [
  {
    "slug": "integration-layer-decides-whether-hospital-ai-works",
    "title": "Your Integration Layer Decides Whether AI Works, Not Your Model"
  },
  {
    "slug": "hospital-ai-data-security-wall",
    "title": "The Data Security Wall: What Large Hospital Groups Are Actually Afraid Of"
  },
  {
    "slug": "30-people-enterprise-grade-agentic-systems",
    "title": "30 People, Enterprise-Grade Agentic Systems: What That Actually Looks Like"
  },
  {
    "slug": "why-nextdot-ai-capability-centre-jamshedpur",
    "title": "Why We Built Nextdot's AI Capability Centre in Jamshedpur"
  },
  {
    "slug": "domain-engineered-vs-general-ai-healthcare",
    "title": "Domain-Engineered vs General AI: Why Pointing a Foundation Model at Healthcare Does Not Work"
  },
  {
    "slug": "how-to-evaluate-an-enterprise-ai-vendor-cxo-checklist",
    "title": "How to Evaluate an Enterprise AI Vendor: A CXO Checklist"
  },
  {
    "slug": "what-is-a-forward-deployed-ai-engineering-pod",
    "title": "What Is a Forward Deployed AI Engineering Pod? (And Why It Beats a Vendor Relationship)"
  },
  {
    "slug": "what-a-prompt-engineer-in-a-creative-pod-does",
    "title": "What a Prompt Engineer Inside a Creative Pod Actually Does All Day"
  },
  {
    "slug": "creative-as-a-system-six-variants-in-a-week",
    "title": "Six Variants in a Week vs One Idea in Six Weeks: The Case for Creative as a System"
  },
  {
    "slug": "the-brief-is-where-a-campaign-is-won-or-lost",
    "title": "The Brief Is Where a Campaign Is Won or Lost: Why We Give It the Most Senior Attention"
  },
  {
    "slug": "ai-agent-governance-gap",
    "title": "The AI Agent Governance Gap: Only 1 in 5 Enterprises Can Manage What They Have Deployed"
  },
  {
    "slug": "designing-the-human-handoff-in-an-agentic-system",
    "title": "Autonomous vs Controlled: How to Design the Human Handoff in an Agentic System"
  },
  {
    "slug": "why-multi-agent-systems-fail-on-coordination-cost",
    "title": "Why Multi-Agent Systems Fail on the Cost of Coordination Rather Than Compute"
  },
  {
    "slug": "what-is-agentic-ai-orchestration",
    "title": "What Is Agentic AI Orchestration? A Plain-English Guide for Decision-Makers"
  },
  {
    "slug": "error-propagation-in-multi-step-ai-agents",
    "title": "Error Propagation in Multi-Step AI: The Failure Mode No Pilot Tests For"
  },
  {
    "slug": "token-costs-caching-model-routing-ai-unit-economics",
    "title": "Token Costs, Caching and Model Routing: How Design Decides Your AI Unit Economics"
  },
  {
    "slug": "what-the-claude-certified-architect-exam-taught-us-about-building-agents",
    "title": "What the Claude Certified Architect Exam Taught Us About Building Agents"
  },
  {
    "slug": "four-parts-of-a-production-ai-agent",
    "title": "The Four Parts of a Production AI Agent (Most Teams Ship Only Three)"
  },
  {
    "slug": "why-enterprise-ai-agent-projects-fail-in-production",
    "title": "Why Enterprise AI Agent Projects Fail in Production (and It Is Rarely the Model)"
  },
  {
    "slug": "ai-scribes-in-indian-languages-why-english-only-fails-in-opd",
    "title": "AI Scribes in Indian Languages: Why an English-Only Tool Fails in the OPD"
  },
  {
    "slug": "hospital-ai-readiness-checklist-8-questions-before-you-deploy",
    "title": "A Hospital AI Readiness Checklist: 8 Questions to Answer Before You Deploy"
  },
  {
    "slug": "building-a-small-language-model-for-healthcare-compliance",
    "title": "Building a Small Language Model for Healthcare Compliance: What We Learned"
  },
  {
    "slug": "from-search-rankings-to-ai-answers-healthcare-discovery-playbook",
    "title": "From Search Rankings to AI Answers: A New Discovery Playbook for Healthcare Brands"
  },
  {
    "slug": "compliant-way-for-indian-doctors-to-be-found-by-ai",
    "title": "The Compliant Way for Indian Doctors to Be Found by AI, Without Advertising"
  },
  {
    "slug": "why-your-hospital-is-invisible-to-ai-assistants",
    "title": "Why Your Hospital Is Invisible to AI Assistants, and How to Fix It"
  },
  {
    "slug": "aeo-vs-seo-what-changed-when-buyers-started-asking-ai",
    "title": "AEO vs SEO: What Changed When Buyers Started Asking AI Instead of Google"
  },
  {
    "slug": "when-production-gets-cheap-taste-becomes-scarce",
    "title": "When Production Gets Cheap, Taste Becomes Scarce: AI and the Future of Creative Work"
  },
  {
    "slug": "ai-voice-agents-never-miss-a-call",
    "title": "The Future of Customer Communication: AI Voice Agents That Never Miss a Call"
  },
  {
    "slug": "ai-doctor-avatars-revolutionizing-healthcare-communication",
    "title": "AI Doctor Avatars: Revolutionizing Healthcare Communication at Scale"
  },
  {
    "slug": "nextcomplyai-compliance-operating-system",
    "title": "NextComplyAI: The Compliance Operating System That Prevents Problems Before They Happen"
  },
  {
    "slug": "what-is-answer-engine-optimisation-aeo",
    "title": "What Is Answer Engine Optimisation (AEO)? A Field Guide for Healthcare and Enterprise"
  },
  {
    "slug": "how-to-check-if-your-business-appears-in-ai-answers",
    "title": "How to Check Whether Your Business Appears in AI Answers (A 10-Minute Method)"
  },
  {
    "slug": "ai-scribe-for-doctors-opd",
    "title": "AI Scribe for Doctors OPD"
  },
  {
    "slug": "healthcare-ai-and-the-dpdp-act",
    "title": "Healthcare AI and the DPDP Act: What Every Hospital CXO Must Understand Before Deploying Agents"
  }
];
